- package.json
- src/app/app.component.html
- src/app/app.component.ts
- src/app/app.module.ts
- src/app/services/contributors.service.ts
- yarn.lock
> Update arlas stack to 3.0.0

- Dockerfile
- scripts/start.sh
> pass the map configuration to arlas-wui docker image

- CONTRIBUTING.md
- LICENCE.txt
- NOTICE.txt
- src/app/app.component.css
- src/app/app.component.spec.ts
- src/app/app.component.ts
- src/app/app.module.ts
- src/app/app.routes.ts
- src/app/components/about/about-dialog.component.css
- src/app/components/about/about.component.css
- src/app/components/about/about.component.spec.ts
- src/app/components/about/about.component.ts
- src/app/components/filters-chips/filters-chips.component.css
- src/app/components/filters-chips/filters-chips.component.spec.ts
- src/app/components/filters-chips/filters-chips.component.ts
- src/app/components/search/search.component.css
- src/app/components/search/search.component.spec.ts
- src/app/components/search/search.component.ts
- src/app/services/contributors.service.ts
- src/main.ts
- src/styles/arlas-wui-theme.scss
- src/styles/histogram.analytics.css
- src/styles/swimlane.css
- src/styles/timeline.css
Add licence header
Add LICENCE.txt
Add CONTRIBUTING.md
Add NOTICE.txt
Fix #32
> Make the project opensource compliant

- Dockerfile
- src/polyfills.ts
- yarn.lock
Add 'npm update' before install dependencies
> Fix docker build error

- src/app/app.component.css
- src/styles.css
- src/styles/donut.css
- yarn.lock
The donut will not grow indefinitely after adding a filter
> Fix the donut component size

- src/app/app.component.css
- src/app/app.component.html
The search bar, refresh button and Analytics toogle button are now
in a div in flex mode to avoid blank betwwen element if one is missing
> Make search bar rendering dynamic

- src/app/components/search/search.component.html
- src/app/components/search/search.component.ts
> Add double quote to search item of autocomplete

- src/config.json
- Add drawType
- Set all timeline's inputs in the configuration
> Fix configuration for map and timeline

- src/app/components/search/search.component.ts
> Fix : not to search when key word is empty

- src/app/app.component.ts
- src/config.json
> Add a mechanism on map dragging to decide whether to apply geosort

- package-lock.json
- package.json
- src/app/components/dataset/dataset.component.css
- src/app/components/dataset/dataset.component.html
- src/app/components/filters-chips/filters-chips.component.html
- src/app/components/filters-chips/filters-chips.component.spec.ts
- src/app/components/search/search.component.html
- src/app/components/search/search.component.spec.ts
- src/app/components/search/search.component.ts
- src/assets/i18n/en.json
- src/assets/i18n/fr.json
- src/styles.css
- src/styles/donut.css
- src/styles/histogram.analytics.css
- src/styles/map.css
- src/styles/resultlist.css
- src/styles/timeline.css
- yarn.lock
> Feature/#84 v7.3.0

- src/app/components/search/search.component.html
- src/app/components/search/search.component.ts
> Wrap search with db quotes for autocomplete

- Dockerfile
> Add healthcheck in docker container

- package-lock.json
- src/app/app.component.html
- src/app/app.component.ts
- src/app/components/search/search.component.ts
- src/config.json
- yarn.lock
> Fix : check existence of objects in conf

- src/styles/histogram.analytics.css
- src/styles/timeline.css
-Timeline : when they are represented as bars & when they are not selectable
-Histograms : when they are not selectable
Fix #105
> Add default css for timeline and histograms of the analytics:

- src/app/app.component.ts
> Fix geosort configuration check

- package-lock.json
- package.json
- src/app/app.component.html
- src/app/app.component.spec.ts
- src/app/app.component.ts
- src/app/app.module.ts
- src/assets/i18n/en.json
- src/assets/i18n/fr.json
- src/styles.css
- src/styles/donut.css
- src/styles/histogram.css
- src/styles/map.css
- src/styles/powerbars.css
- src/styles/resultlist.css
- src/styles/timeline.css
- yarn.lock
Add Gauge component
Fix some css rules
> Update toolkit version to 9.2.0

- src/app/app.component.html
- src/config.json
> Add the map input :'defaultBasemapStyle' & 'basemapStyles'

- scripts/start.sh
- src/config.json
> Add env variables within the config file to set at docker run

- src/app/app.component.html
- src/app/app.component.ts
> Add groupsDisplayStatusMap in analytics board

- package-lock.json
> Update lock files

- scripts/start.sh
- src/index.html
> Add environment variable for Google Analytics Key

- nginx/default.conf
- scripts/start.sh
> Support serving app under URL base-path

- package-lock.json
- package.json
- src/app/app.component.html
- src/app/app.component.ts
> Add spinner configuration & update stack to 12.2.1

- src/index.html
> Use variable for Google analytics key

- package-lock.json
- package.json
- src/styles/donut.css
> Set donuts size in AB

- package-lock.json
- package.json
- src/app/app.component.css
- src/app/app.component.html
- src/app/app.component.ts
- src/config.json
- src/styles.css
> Add a button to zoom to data extent

- package-lock.json
- package.json
- scripts/start.sh
- src/app/app.module.ts
- src/index.html
> Use routing from toolkit

- package-lock.json
- package.json
Workaround taken from :
https://stackoverflow.com/questions/60780664/could-not-find-plugin-proposal-numeric-separator
> update lock file

- nginx/default.conf
> Fix rewrite uncorrectly guessing protocol

- package-lock.json
- scripts/start.sh
- src/config.json
> Enable collection configuration through env var

- package-lock.json
- src/app/app.component.ts
> Fix id in resultlist sort + update lock files

- angular.json
- package-lock.json
- src/silent-refresh.html
> Add silent refresh page to refresh tokens

- src/app/app.component.ts
> Fix import geometries as filter

- release.sh
Fix #258 
@sebbousquet @MohamedHamouGisaia 
I think it should be fine, what do you think?
> Publish to npm in release

- src/app/components/configs-list/configs-list.component.html
> Fix 'manage dashboard' button position

- package-lock.json
- package.json
- src/app/app.component.ts
- src/styles.css
> Use configuration name as App name

- src/styles/histogram.css
- src/styles/resultlist.css
> Fix result list detail display

- src/app/app.component.html
- src/app/app.component.ts
- src/app/components/left-menu/left-menu.component.ts
> Add the possibility to override the ARLAS version with an input

- package-lock.json
- package.json
- src/app/app.component.html
- src/app/app.component.ts
- src/app/components/left-menu/left-menu.component.ts
> Share visible layers on the map only

- package-lock.json
- package.json
- src/app/app.component.html
- src/app/app.component.ts
- Pass version to left-menu component
- Fix legend status that is vehiculated to share component
> Fix 2 bugs

- package-lock.json
> Upgrade to components 19.0.3 to fix fill icon color (legend)

- src/app/app.component.ts
> Remove double popup on feature click

- package-lock.json
- package.json
- src/app/app.component.html
- src/app/app.component.ts
- src/styles/arlas-wui-theme.scss
- src/styles/filter.css
- src/styles/resultlist.css
> Display count of all configured collections

- src/app/app.component.ts
> Fix retrocomaptibility count unit

- src/app/app.component.html
- src/app/app.component.ts
> Use mapcomponent html output

- package-lock.json
- src/app/app.component.css
- src/styles/map.css
> Fix map credits display

- scripts/start.sh
Causing trouble with embarked config files
Fix #424
> Remove old setting for persistence

- package-lock.json
- package.json
> Prepare release of the beta version of 21.0.0

- package-lock.json
- package.json
- src/app/app.component.ts
Needs release of ARLAS-wui-toolkit
- Fix #403
> Store the visible visualisation sets in the url

- package-lock.json
- package.json
- src/app/app.component.css
- src/app/app.component.html
- src/app/app.component.ts
- src/app/services/contributors.service.ts
> Adapt mapSettingsService to multi-collection

- src/app/app.component.html
- src/app/app.component.ts
- src/app/components/left-menu/left-menu.component.html
- src/app/components/left-menu/left-menu.component.ts
- src/settings.yaml
> Add collections in download

- README.md
> Fix 'Get started link'

- package-lock.json
- package.json
> Upgrade toolkit to 22.0.4

- src/styles.css
> Fix coordinates position

- package-lock.json
- package.json
- src/app/app.component.html
- src/app/app.component.ts
> Dowload layer's data

- angular.json
> fix: add favicon in app build

- src/styles.css
> fix: center metric legend text

- src/styles/resultlist.css
> fix: add scroll when the text is wider than the popup

- package-lock.json
- package.json
fix special chars in detail result list
> Upgrade to toolkit 20.1.2 to

- src/assets/i18n/en.json
- src/assets/i18n/fr.json
> fix: missing translation

- src/app/app.component.ts
> Stringify ids of feature in order to be able to highlight the div in list

- src/app/app.component.css
> fix: basemap container badly positioned

- package-lock.json
- package.json
- src/app/services/visualize.service.ts
> Fix: support geojson geom in get bounds method

- .github/ISSUE_TEMPLATE/bug-report.yaml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature-request.yaml
Add issue and feature request templates
> docs: add issue template

- .github/ISSUE_TEMPLATE/bug-report.yaml
- .github/ISSUE_TEMPLATE/feature-request.yaml
The wrong label was set for this repo
> fix: label when creating issue

- package-lock.json
- package.json
- src/app/app.component.html
- src/app/app.component.scss
Fix integration part of #613 
Still need to decide the deired behaviour when too many chips
> feat: ergo filters

- package-lock.json
- package.json
- src/app/app.component.html
- src/app/app.component.scss
- src/app/components/left-menu/left-menu.component.scss
- src/styles/variables.scss
> feat: integrate search bar

- package-lock.json
- package.json
- src/app/app.component.html
- src/app/app.component.scss
- src/app/app.component.ts
- src/styles.scss
- src/styles/app/sizes.scss
> feat: integrate shortcuts into top bar

- package-lock.json
- package.json
- src/app/app.component.html
- src/app/app.component.scss
- src/app/app.component.ts
- src/app/components/left-menu/left-menu.component.html
- src/styles/map.scss
- src/styles/resultlist.css
- src/styles/variables.scss
> feat: add new ergo for map controls

- package-lock.json
- package.json
- src/app/app.module.ts
- src/app/components/arlas-wui-root/arlas-wui-root.component.html
- src/app/components/arlas-wui-root/arlas-wui-root.component.scss
- src/app/components/arlas-wui-root/arlas-wui-root.component.ts
- src/app/components/map/aoi-dimensions/aoi-dimensions.component.html
- src/app/components/map/aoi-dimensions/aoi-dimensions.component.scss
- src/app/components/map/aoi-dimensions/aoi-dimensions.component.ts
- src/app/components/map/aoi-dimensions/aoi-dimensions.pipes.ts
- src/assets/i18n/en.json
- src/assets/i18n/fr.json
- src/public-api.ts
> Add Area and Distances info for AOIs

- src/styles.scss
- src/styles/app/sizes.scss
- use title size for description
> fix: realign metrics

- src/app/components/arlas-wui-root/arlas-wui-root.component.html
- src/app/components/arlas-wui-root/arlas-wui-root.component.scss
> fix: change map selection icons

- src/app/app.component.scss
- src/app/components/arlas-wui-root/arlas-wui-root.component.html
> fix: icon and tooltip

- package-lock.json
- package.json
- scripts/start.sh
- src/app/components/arlas-wui-root/arlas-wui-root.component.ts
- src/environments/prod/settings.yaml
> feat: check download endpoint

- package-lock.json
- package.json
- src/app/components/arlas-wui-root/arlas-wui-root.component.ts
> Fix initial bbox of bbox generator

- docs/arlas-wui-configuration.md
- scripts/start.sh
- src/app/components/arlas-wui-root/arlas-wui-root.component.ts
- src/app/components/left-menu/left-menu.component.html
- src/app/components/left-menu/left-menu.component.ts
- src/environments/prod/settings.yaml
- src/settings.yaml
> Make configurable the display of config-list

- src/assets/browser-compatibility/browser-compatibility.component.css
- src/assets/browser-compatibility/browser-compatibility.component.html
- src/index.html
> feat: check browser comptibility before angular app run

- src/styles/map.scss
> fix: enforce style by specificity

- scripts/start.sh
> Fix: geocoding conf in start.sh

- src/app/components/arlas-wui-root/arlas-wui-root.component.scss
- src/styles/map.scss
> fix: restore position of map controls

- src/app/components/arlas-wui-root/arlas-wui-root.component.scss
> Fix: list wrapper height

- src/app/components/arlas-wui-root/arlas-wui-root.component.html
- src/app/components/arlas-wui-root/arlas-wui-root.component.ts
- Fix https://github.com/gisaia/ARLAS-wui/issues/673
> Feat: use liste detail on feature click

- package-lock.json
- package.json
- src/app/components/arlas-wui-root/arlas-wui-root.component.html
- src/app/components/arlas-wui-root/arlas-wui-root.component.ts
> feat: implements zoom to strategy

- src/app/components/arlas-wui-root/arlas-wui-root.component.html
- src/app/components/arlas-wui-root/arlas-wui-root.component.ts
- src/app/services/contributors.service.ts
> Feat: use new search contributor

- src/app/components/arlas-wui-root/arlas-wui-root.component.ts
> Feat: wait for dom element before getBoudingClientRect

- package-lock.json
- package.json
- src/app/components/arlas-wui-root/arlas-wui-root.component.ts
- Fix #868 
Need new contributors
> Feat: ingore collab in getFilterForCount

- .github/workflows/trivy.yml
- package-lock.json
- package.json
- src/app/components/arlas-wui-root/arlas-wui-root.component.ts
Need new toolkit
- Fix https://github.com/gisaia/ARLAS-wui/issues/894
> Feat: add displayFieldName in download source

- .github/workflows/release.yml
- release.sh
> ci: add release with github action

- release.sh
as the input device is not a TTY
> Remove -it from docker option

- .github/workflows/main.yml
- .github/workflows/release.yml
- .github/workflows/trivy.yml
- docs/arlas-wui-configuration.md
- docs/arlas-wui-security.md
> Docs: update security

- src/app/components/arlas-wui-root/arlas-wui-root.component.html
- src/assets/about/about_en.md
- src/assets/about/about_fr.md
> fix: avoid left menu closing and add missing maplibre in about

- src/app/components/arlas-map/arlas-map.component.ts
To match the current develop version of arlas-web-contributors
> Fix: wrong typing

- package.json
- src/app/components/arlas-wui-root/arlas-wui-root.component.html
- src/app/components/arlas-wui-root/arlas-wui-root.component.ts
- src/app/components/export-data-dialog/export-data-dialog.component.html
- src/app/components/export-data-dialog/export-data-dialog.component.scss
- src/app/components/export-data-dialog/export-data-dialog.component.spec.ts
- src/app/components/export-data-dialog/export-data-dialog.component.ts
- src/assets/i18n/en.json
- src/assets/i18n/es.json
- src/assets/i18n/fr.json
- close #958 
need  toolkit release to have new design.
[Capture vidéo du 11-04-2025 16:49:12.webm](https://github.com/user-attachments/assets/e12c451b-95d6-4abd-b822-ad53c7e1ae23)
> feat: merge share and dialog modal

- package-lock.json
- package.json
- packages/cloud/package.json
- packages/opensource/package.json
> build(deps): bump toolkit and map

- docker/Dockerfile
- package-lock.json
- package.json
- packages/cloud/package.json
- packages/opensource/package.json
- src/app/components/arlas-map/arlas-map.component.ts
- src/app/services/cog.service.ts
- src/app/services/map.service.ts
- src/settings.yaml
> implement interaction between map and timeline

- src/app/app.component.ts
- src/app/app.module.ts
- src/app/components/arlas-analytics/arlas-analytics.component.ts
- src/app/components/arlas-list/arlas-list.component.ts
- src/app/components/arlas-map/arlas-map.component.ts
- src/app/components/arlas-wui-root/arlas-wui-root.component.ts
- src/app/components/configs-list/configs-list.component.ts
- src/app/components/geocoding/geocoding.component.ts
- src/app/components/left-menu/left-menu.component.ts
- src/app/components/map/raster-layers-manager/rasters-manager.component.ts
- src/app/pipes/get-resultlist-config.pipe.ts
- Fix #1005 
Needs gisaia/ARLAS-web-components#1010 to be merged and released first
> fix: recalculate extent when list opened to update visible items on map
